In [225]:
# importing libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer

In [226]:
# loading dataset
df = pd.read_csv(r"C:\Users\rasika\Downloads\anime.csv")
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [227]:
# Dataset Summary
df.info() # numbers of entries, number of columns and there datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [228]:
# Summary statistics
df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [229]:
# checking for missing values
df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [230]:
# replacing missing values with mode
df['genre'] = df['genre'].fillna(df['genre'].mode()[0])

In [247]:
# replacing missing values with mode
df['type'] = df['type'].fillna(df['type'].mode()[0])
df['type'].dtype

dtype('int64')

In [232]:
# replacing missing values with mean
df['rating'] = df['rating'].fillna(df['rating'].mean())

#### Feature Encoding

In [250]:
le = LabelEncoder()
df['type'] = le.fit_transform(df['type'])
print(df.head())
print(df['type'].dtype)

   anime_id                              name  \
0     32281                    Kimi no Na wa.
1      5114  Fullmetal Alchemist: Brotherhood
2     28977                          Gintama°
3      9253                       Steins;Gate
4      9969                     Gintama&#039;

                                               genre  type  episodes  rating  \
0               Drama, Romance, School, Supernatural     0       1.0    9.37
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     5      64.0    9.26
2  Action, Comedy, Historical, Parody, Samurai, S...     5      51.0    9.25
3                                   Sci-Fi, Thriller     5      24.0    9.17
4  Action, Comedy, Historical, Parody, Samurai, S...     5      51.0    9.16

   members
0   200630
1   793665
2   114262
3   673572
4   151266
int64

In [251]:
tfidf = TfidfVectorizer(stop_words='english')
genre_matrix = tfidf.fit_transform(df['genre'])
genre_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 40480 stored elements and shape (12294, 46)>

In [252]:
# feature Extraction
tfidf.get_feature_names_out()

array(['action', 'adventure', 'ai', 'arts', 'cars', 'comedy', 'dementia',
       'demons', 'drama', 'ecchi', 'fantasy', 'fi', 'game', 'harem',
       'hentai', 'historical', 'horror', 'josei', 'kids', 'life', 'magic',
       'martial', 'mecha', 'military', 'music', 'mystery', 'parody',
       'police', 'power', 'psychological', 'romance', 'samurai', 'school',
       'sci', 'seinen', 'shoujo', 'shounen', 'slice', 'space', 'sports',
       'super', 'supernatural', 'thriller', 'vampire', 'yaoi', 'yuri'],
      dtype=object)

In [253]:
tfidf_df = pd.DataFrame(genre_matrix.toarray(), columns=tfidf.get_feature_names_out())
tfidf_df.head()

,action,adventure,ai,arts,cars,comedy,dementia,demons,drama,ecchi,...,shounen,slice,space,sports,super,supernatural,thriller,vampire,yaoi,yuri
0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.440247,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.544416,0.000000,0.0,0.0,0.0
1,0.294649,0.317607,0.0,0.0,0.0,0.000000,0.0,0.0,0.335834,0.0,...,0.350987,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
2,0.250631,0.000000,0.0,0.0,0.0,0.200766,0.0,0.0,0.000000,0.0,...,0.298553,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
3,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.000000,0.833769,0.0,0.0,0.0
4,0.250631,0.000000,0.0,0.0,0.0,0.200766,0.0,0.0,0.000000,0.0,...,0.298553,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [254]:
#Converting object column to nuimeric type
df['episodes'] = pd.to_numeric(df['episodes'], errors='coerce')

#replacing missing('unknown') with median
df['episodes'] = df['episodes'].fillna(df['episodes'].median())

In [256]:
# Minmaxscaling
mm = MinMaxScaler()
num_column = df.drop('anime_id', axis = 1).select_dtypes(include = ['int', 'float']).columns
df[num_column] = mm.fit_transform(df[num_column])
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",0.0,0.000000,0.924370,0.197872
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",1.0,0.034673,0.911164,0.782770
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",1.0,0.027518,0.909964,0.112689
3,9253,Steins;Gate,"Sci-Fi, Thriller",1.0,0.012658,0.900360,0.664325
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",1.0,0.027518,0.899160,0.149186

In [257]:
# Combining all features
from scipy.sparse import hstack
feature_matrix = hstack([genre_matrix, df[['episodes']]])
feature_matrix

<COOrdinate sparse matrix of dtype 'float64'
	with 47097 stored elements and shape (12294, 47)>

In [260]:
# Calculating cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(feature_matrix)

In [262]:
# Index mapping
indices = pd.Series(df.index, index=df['name']).drop_duplicates()

In [263]:
idx = indices['Naruto']
idx

np.int64(841)

#### Recommendation Function

In [264]:
def recommend_anime(title, top_n=10):

    idx = indices[title]

    similarity_scores = list(enumerate(cosine_sim[idx]))

    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    similarity_scores = similarity_scores[1:top_n+1]

    anime_indices = [i[0] for i in similarity_scores]

    return df[['name', 'genre','rating']].iloc[anime_indices]

In [265]:
recommend_anime("Naruto")

,name,genre,rating
615,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",0.752701
486,Boruto: Naruto the Movie,"Action, Comedy, Martial Arts, Shounen, Super P...",0.763505
1103,Boruto: Naruto the Movie - Naruto ga Hokage ni...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.721489
1343,Naruto x UT,"Action, Comedy, Martial Arts, Shounen, Super P...",0.709484
1472,Naruto: Shippuuden Movie 4 - The Lost Tower,"Action, Comedy, Martial Arts, Shounen, Super P...",0.703481
1573,Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.699880
2458,Naruto Shippuuden: Sunny Side Battle,"Action, Comedy, Martial Arts, Shounen, Super P...",0.671068
2997,Naruto Soyokazeden Movie: Naruto to Mashin to ...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.653061
7628,Kyutai Panic Adventure!,"Action, Martial Arts, Shounen, Super Power",0.424970
1796,Rekka no Honoo,"Action, Adventure, Martial Arts, Shounen, Supe...",0.692677

In [266]:
# Getting similarity score
similarity_scores = list(enumerate(cosine_sim[idx]))
similarity_scores

[(0, np.float64(0.0)),
 (1, np.float64(0.17679531427181838)),
 (2, np.float64(0.18914552516499633)),
 (3, np.float64(0.0015145913881251087)),
 (4, np.float64(0.18914552516499633)),
 (5, np.float64(0.17761953313782225)),
 (6, np.float64(0.6675139007799272)),
 (7, np.float64(0.007165539516063959)),
 (8, np.float64(0.18592427158165037)),
 (9, np.float64(0.1867104846801746)),
 (10, np.float64(0.0015145913881251087)),
 (11, np.float64(0.1617112910914623)),
 (12, np.float64(0.19790044033940493)),
 (13, np.float64(0.4255120288333097)),
 (14, np.float64(0.17859398946712368)),
 (15, np.float64(0.0)),
 (16, np.float64(0.12045654546354129)),
 (17, np.float64(0.0005927064043219174)),
 (18, np.float64(0.0)),
 (19, np.float64(0.4190008815555693)),
 (20, np.float64(0.20602593768758568)),
 (21, np.float64(0.4875198007947922)),
 (22, np.float64(0.12779381923822933)),
 (23, np.float64(0.4361595277118477)),
 (24, np.float64(0.13265200489887816)),
 (25, np.float64(0.04582925468553277)),
 (26, np.float64(0.04533189889556167)),
 (27, np.float64(0.0005927064043219174)),
 (28, np.float64(0.0016462710561398748)),
 (29, np.float64(0.14749102406006093)),
 (30, np.float64(0.1713231616947635)),
 (31, np.float64(0.0007902676659215948)),
 (32, np.float64(0.2029505229993158)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0007902676659215948)),
 (35, np.float64(0.0)),
 (36, np.float64(0.07745585650285564)),
 (37, np.float64(0.07172807325369032)),
 (38, np.float64(0.0048036911717344154)),
 (39, np.float64(0.22555857683688357)),
 (40, np.float64(0.002370389497756427)),
 (41, np.float64(0.07946256157987694)),
 (42, np.float64(0.33785039500599523)),
 (43, np.float64(0.17859398946712368)),
 (44, np.float64(0.20288617747450877)),
 (45, np.float64(0.06336054286265104)),
 (46, np.float64(0.0007902676659215948)),
 (47, np.float64(0.000658560776516282)),
 (48, np.float64(0.0)),
 (49, np.float64(0.0007244145503255228)),
 (50, np.float64(0.000658560776516282)),
 (51, np.float64(0.11701987288224998)),
 (52, np.float64(0.04926989240663653)),
 (53, np.float64(0.0016462710561398752)),
 (54, np.float64(0.0015804319399358926)),
 (55, np.float64(0.43978720127953347)),
 (56, np.float64(0.0007902676659215948)),
 (57, np.float64(0.000658560776516282)),
 (58, np.float64(0.19508815246204705)),
 (59, np.float64(0.0)),
 (60, np.float64(0.0)),
 (61, np.float64(0.14422726137644531)),
 (62, np.float64(0.08461952228951945)),
 (63, np.float64(0.1859901004890572)),
 (64, np.float64(0.22524013716923394)),
 (65, np.float64(0.18592427158165037)),
 (66, np.float64(0.05810991906825233)),
 (67, np.float64(0.06396338239256615)),
 (68, np.float64(0.0007902676659215948)),
 (69, np.float64(0.049714484658969375)),
 (70, np.float64(0.0)),
 (71, np.float64(0.0)),
 (72, np.float64(0.19508815246204705)),
 (73, np.float64(0.06330584937730405)),
 (74, np.float64(0.6171115018525477)),
 (75, np.float64(0.05751194538859833)),
 (76, np.float64(0.2731704769186282)),
 (77, np.float64(0.06637528186455971)),
 (78, np.float64(0.08238021640521676)),
 (79, np.float64(0.18333725733785425)),
 (80, np.float64(0.000658560776516282)),
 (81, np.float64(0.0)),
 (82, np.float64(0.14861579322954874)),
 (83, np.float64(0.04805765655911001)),
 (84, np.float64(0.11751601361397468)),
 (85, np.float64(0.0)),
 (86, np.float64(0.6205350738429164)),
 (87, np.float64(0.22555857683688357)),
 (88, np.float64(0.05767558901424884)),
 (89, np.float64(0.0930760854659458)),
 (90, np.float64(0.10201383734438481)),
 (91, np.float64(0.0015804319399358926)),
 (92, np.float64(0.07381557990441577)),
 (93, np.float64(0.0015804319399358926)),
 (94, np.float64(0.11957680522444543)),
 (95, np.float64(0.17778528701254262)),
 (96, np.float64(0.0007244145503255228)),
 (97, np.float64(0.0648334128041343)),
 (98, np.float64(0.07143416104971181)),
 (99, np.float64(0.07614670077996262)),
 (100, np.float64(0.19674297771849675)),
 (101, np.float64(0.22181089811071159)),
 (102, np.float64(0.0)),
 (103, np.float64(0.07153435951722034)),
 (104, np.float64(0.2219486115531364)),
 (105, np.float64(0.1435112581999062)),
 (106, np.float64(0.5692187579540008)),
 (107, np.float64(0.0)),
 (108, np.float64(0.07304271159243785)),
 (109, np.float64(0.0007244145503255232)),
 (110, np.float64(0.11314402016082596)),
 (111, np.float64(0.0030284551029139584)),
 (112, np.float64(0.6636572571078009)),
 (113, np.float64(0.2492646293743505)),
 (114, np.float64(0.0007244145503255228)),
 (115, np.float64(0.0798859456880426)),
 (116, np.float64(0.06242879659248099)),
 (117, np.float64(0.0)),
 (118, np.float64(0.04556748190033296)),
 (119, np.float64(0.0021070996535031234)),
 (120, np.float64(0.6308725193752669)),
 (121, np.float64(0.10167192302629595)),
 (122, np.float64(0.19508815246204705)),
 (123, np.float64(0.040158180405393006)),
 (124, np.float64(0.000724414550325523)),
 (125, np.float64(0.09359529095410725)),
 (126, np.float64(0.0)),
 (127, np.float64(0.20923922190399935)),
 (128, np.float64(0.003225823902473263)),
 (129, np.float64(0.0)),
 (130, np.float64(0.0)),
 (131, np.float64(0.05773638378013445)),
 (132, np.float64(0.0)),
 (133, np.float64(0.21185408779509543)),
 (134, np.float64(0.06674079699835439)),
 (135, np.float64(0.12314809248142729)),
 (136, np.float64(0.07958130870796912)),
 (137, np.float64(0.10965333419769116)),
 (138, np.float64(0.2091740948459324)),
 (139, np.float64(0.2029505229993158)),
 (140, np.float64(0.15994472108737173)),
 (141, np.float64(0.19347931613241992)),
 (142, np.float64(0.0007902676659215948)),
 (143, np.float64(0.28662955370164256)),
 (144, np.float64(0.0015145913881251087)),
 (145, np.float64(0.6604699616451298)),
 (146, np.float64(0.6608530913586563)),
 (147, np.float64(0.13299163257948732)),
 (148, np.float64(0.2029505229993158)),
 (149, np.float64(0.0015804319399358921)),
 (150, np.float64(0.16650676916953766)),
 (151, np.float64(0.05423694297925838)),
 (152, np.float64(0.07286290130576507)),
 (153, np.float64(0.14811114752060642)),
 (154, np.float64(0.06667511785695936)),
 (155, np.float64(0.0)),
 (156, np.float64(0.05778422539432698)),
 (157, np.float64(0.0025678344913961787)),
 (158, np.float64(0.05344451930634819)),
 (159, np.float64(0.15413833817374667)),
 (160, np.float64(0.0009219716831772703)),
 (161, np.float64(0.0007244145503255228)),
 (162, np.float64(0.22666133379222558)),
 (163, np.float64(0.28662955370164256)),
 (164, np.float64(0.05038120828156587)),
 (165, np.float64(0.18848770705471282)),
 (166, np.float64(0.10122241869402344)),
 (167, np.float64(0.04706639911914804)),
 (168, np.float64(0.0016462710561398748)),
 (169, np.float64(0.0)),
 (170, np.float64(0.0)),
 (171, np.float64(0.12794550073568572)),
 (172, np.float64(0.000724414550325523)),
 (173, np.float64(0.19308098188719985)),
 (174, np.float64(0.0)),
 (175, np.float64(0.7390296736049681)),
 (176, np.float64(0.14985565121989797)),
 (177, np.float64(0.0007902676659215948)),
 (178, np.float64(0.6677489870886906)),
 (179, np.float64(0.18332120008578076)),
 (180, np.float64(0.04777887631717355)),
 (181, np.float64(0.07146851327585715)),
 (182, np.float64(0.8914002498100578)),
 (183, np.float64(0.258802065285755)),
 (184, np.float64(0.26217934162002)),
 (185, np.float64(0.18338647294277594)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.2029505229993158)),
 (189, np.float64(0.0)),
 (190, np.float64(0.06422609937618856)),
 (191, np.float64(0.0590456094110029)),
 (192, np.float64(0.06119887599196216)),
 (193, np.float64(0.22130254422107679)),
 (194, np.float64(0.5525681982992253)),
 (195, np.float64(0.08296591603694069)),
 (196, np.float64(0.0)),
 (197, np.float64(0.04782230304410975)),
 (198, np.float64(0.05478667847783867)),
 (199, np.float64(0.000724414550325523)),
 (200, np.float64(0.2159436290823806)),
 (201, np.float64(0.0016462710561398748)),
 (202, np.float64(0.6604699616451298)),
 (203, np.float64(0.06847192184671798)),
 (204, np.float64(0.0015804319399358926)),
 (205, np.float64(0.18848770705471282)),
 (206, np.float64(0.9373467960404539)),
 (207, np.float64(0.20845350011451572)),
 (208, np.float64(0.0)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0016462710561398752)),
 (211, np.float64(0.06414131174010362)),
 (212, np.float64(0.28662955370164256)),
 (213, np.float64(0.11163837164704109)),
 (214, np.float64(0.19598777087501154)),
 (215, np.float64(6.585706503956701e-05)),
 (216, np.float64(0.18592427158165037)),
 (217, np.float64(0.0)),
 (218, np.float64(0.15726584112768507)),
 (219, np.float64(0.06797949514968979)),
 (220, np.float64(0.07719858932649291)),
 (221, np.float64(0.11786741071432127)),
 (222, np.float64(0.12530722822857923)),
 (223, np.float64(0.04843493887053093)),
 (224, np.float64(0.1651158100118697)),
 (225, np.float64(0.08706099967174534)),
 (226, np.float64(0.11685993487302838)),
 (227, np.float64(0.18848770705471282)),
 (228, np.float64(0.0016462710561398748)),
 (229, np.float64(0.00019757095574697965)),
 (230, np.float64(0.000724414550325523)),
 (231, np.float64(0.6170457382370999)),
 (232, np.float64(0.21383399872761236)),
 (233, np.float64(0.05016860598435591)),
 (234, np.float64(0.22666133379222558)),
 (235, np.float64(0.04627687672091011)),
 (236, np.float64(0.06451929516980145)),
 (237, np.float64(0.20282176958241888)),
 (238, np.float64(0.0015145913881251087)),
 (239, np.float64(0.0542462302769317)),
 (240, np.float64(0.041029015635354535)),
 (241, np.float64(0.6170457382370999)),
 (242, np.float64(0.08097022334241745)),
 (243, np.float64(0.061854576439800725)),
 (244, np.float64(0.0)),
 (245, np.float64(0.09288043049822763)),
 (246, np.float64(0.0003292841283435786)),
 (247, np.float64(0.0)),
 (248, np.float64(0.06212797717444539)),
 (249, np.float64(0.15262730143690162)),
 (250, np.float64(0.000658560776516282)),
 (251, np.float64(0.4828412510297104)),
 (252, np.float64(0.1543527645794958)),
 (253, np.float64(0.15428693088071546)),
 (254, np.float64(0.19823369206609393)),
 (255, np.float64(0.27308375475311897)),
 (256, np.float64(0.0007902676659215948)),
 (257, np.float64(0.22524013716923394)),
 (258, np.float64(0.06427939528793282)),
 (259, np.float64(0.053026559754162414)),
 (260, np.float64(0.7387319514751336)),
 (261, np.float64(0.11825234183636807)),
 (262, np.float64(0.077921589246548)),
 (263, np.float64(0.06613840308667267)),
 (264, np.float64(0.15726584112768507)),
 (265, np.float64(0.0)),
 (266, np.float64(0.08231530830361307)),
 (267, np.float64(0.047502037878404214)),
 (268, np.float64(0.22181089811071159)),
 (269, np.float64(0.06785498976360876)),
 (270, np.float64(0.0007902676659215948)),
 (271, np.float64(0.8914002498100578)),
 (272, np.float64(0.10384399279429535)),
 (273, np.float64(0.14092987247161606)),
 (274, np.float64(0.15428693088071546)),
 (275, np.float64(0.10043840241680267)),
 (276, np.float64(0.06319312239713912)),
 (277, np.float64(0.0032916077277266595)),
 (278, np.float64(0.0015145913881251087)),
 (279, np.float64(0.20132330534658838)),
 (280, np.float64(0.06626914336691736)),
 (281, np.float64(0.6048994698430619)),
 (282, np.float64(0.07245229219595554)),
 (283, np.float64(0.0)),
 (284, np.float64(0.06723162928420277)),
 (285, np.float64(0.0)),
 (286, np.float64(0.15192836848309574)),
 (287, np.float64(0.005132125274863845)),
 (288, np.float64(0.2770454744534883)),
 (289, np.float64(0.0)),
 (290, np.float64(0.22103514132073188)),
 (291, np.float64(0.0025020217451832555)),
 (292, np.float64(0.20582858848794497)),
 (293, np.float64(0.15428693088071546)),
 (294, np.float64(0.10201383734438481)),
 (295, np.float64(0.21504292416304088)),
 (296, np.float64(0.07217613965757184)),
 (297, np.float64(0.06716767423368264)),
 (298, np.float64(0.06785498976360876)),
 (299, np.float64(0.06667515317524265)),
 (300, np.float64(0.06621507316397683)),
 (301, np.float64(0.33765974344142075)),
 (302, np.float64(0.1163637836219771)),
 (303, np.float64(0.12607252794447596)),
 (304, np.float64(0.36714508725095046)),
 (305, np.float64(0.07823941639183256)),
 (306, np.float64(0.18592427158165037)),
 (307, np.float64(0.27822187888533056)),
 (308, np.float64(0.07731899874429805)),
 (309, np.float64(0.0846850831874707)),
 (310, np.float64(0.05688062758716908)),
 (311, np.float64(0.15654429518286858)),
 (312, np.float64(0.0)),
 (313, np.float64(0.05475587350201638)),
 (314, np.float64(0.003225823902473263)),
 (315, np.float64(0.054508899697122526)),
 (316, np.float64(0.127983131559013)),
 (317, np.float64(0.06325896989178362)),
 (318, np.float64(0.17577761891563198)),
 (319, np.float64(0.0015804319399358921)),
 (320, np.float64(0.04718714029171272)),
 (321, np.float64(0.000658560776516282)),
 (322, np.float64(0.04836297043971125)),
 (323, np.float64(0.000724414550325523)),
 (324, np.float64(0.18332120008578076)),
 (325, np.float64(0.04991549305604619)),
 (326, np.float64(0.06948864709878697)),
 (327, np.float64(0.0)),
 (328, np.float64(0.00013171407023613568)),
 (329, np.float64(0.15661012853977835)),
 (330, np.float64(0.06501496642321099)),
 (331, np.float64(0.12530722822857923)),
 (332, np.float64(0.18848770705471282)),
 (333, np.float64(0.5941873088992133)),
 (334, np.float64(0.0016462710561398748)),
 (335, np.float64(0.0013829062167613575)),
 (336, np.float64(0.0)),
 (337, np.float64(0.001514591388125109)),
 (338, np.float64(0.000724414550325523)),
 (339, np.float64(0.24919964173050402)),
 (340, np.float64(0.09195155097203223)),
 (341, np.float64(0.047098910999732985)),
 (342, np.float64(0.15692430096836724)),
 (343, np.float64(0.20973247931156627)),
 (344, np.float64(0.15428693088071546)),
 (345, np.float64(0.15428693088071546)),
 (346, np.float64(0.905340921079741)),
 (347, np.float64(0.05822331566260967)),
 (348, np.float64(0.15726584112768507)),
 (349, np.float64(0.09048103393777193)),
 (350, np.float64(0.2567703022920777)),
 (351, np.float64(0.0016462710561398748)),
 (352, np.float64(0.6512064278100709)),
 (353, np.float64(0.0750592326225125)),
 (354, np.float64(0.06422609937618856)),
 (355, np.float64(0.5513737485063366)),
 (356, np.float64(0.10354992756121292)),
 (357, np.float64(0.20371778455037973)),
 (358, np.float64(0.06677869557874666)),
 (359, np.float64(0.12484822242004108)),
 (360, np.float64(0.10043840241680267)),
 (361, np.float64(0.20287810571055453)),
 (362, np.float64(0.0)),
 (363, np.float64(0.34851663063885047)),
 (364, np.float64(0.20759551062660106)),
 (365, np.float64(0.0)),
 (366, np.float64(0.19391868530754833)),
 (367, np.float64(0.21502651988166893)),
 (368, np.float64(0.15726584112768507)),
 (369, np.float64(0.0007244145503255228)),
 (370, np.float64(0.0)),
 (371, np.float64(0.26670740238231205)),
 (372, np.float64(0.06548345483105418)),
 (373, np.float64(0.05574423305528036)),
 (374, np.float64(0.1739714487523974)),
 (375, np.float64(0.16760439489194642)),
 (376, np.float64(0.05349448295404565)),
 (377, np.float64(0.11623213996362747)),
 (378, np.float64(0.15428693088071546)),
 (379, np.float64(0.1964454159633629)),
 (380, np.float64(0.1747769659726689)),
 (381, np.float64(0.22865006445190417)),
 (382, np.float64(0.04634257117131617)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0007244145503255228)),
 (385, np.float64(0.11000594143086265)),
 (386, np.float64(0.18037449383952314)),
 (387, np.float64(0.00019757095574697963)),
 (388, np.float64(0.07065364354945272)),
 (389, np.float64(0.09630279592851619)),
 (390, np.float64(0.30720303794866455)),
 (391, np.float64(0.10043840241680267)),
 (392, np.float64(0.000724414550325523)),
 (393, np.float64(0.0590456094110029)),
 (394, np.float64(0.10201383734438481)),
 (395, np.float64(0.11186971709454045)),
 (396, np.float64(0.0654178471124644)),
 (397, np.float64(0.1651158100118697)),
 (398, np.float64(0.3098970112720893)),
 (399, np.float64(0.2017882076230453)),
 (400, np.float64(0.5722406018207762)),
 (401, np.float64(0.06797949514968979)),
 (402, np.float64(0.10624191870355736)),
 (403, np.float64(0.06628085988327788)),
 (404, np.float64(0.15575669538496908)),
 (405, np.float64(0.08546975941903864)),
 (406, np.float64(0.07245229219595554)),
 (407, np.float64(0.06601064264633363)),
 (408, np.float64(0.08446699808760813)),
 (409, np.float64(0.10386535689348197)),
 (410, np.float64(0.048543884827677686)),
 (411, np.float64(0.0001317140702361357)),
 (412, np.float64(0.07194541965696095)),
 (413, np.float64(0.0017779447426883295)),
 (414, np.float64(0.0025020217451832555)),
 (415, np.float64(0.0)),
 (416, np.float64(0.5533464157632954)),
 (417, np.float64(0.10173150593832733)),
 (418, np.float64(0.0639163789612293)),
 (419, np.float64(0.05478667847783867)),
 (420, np.float64(0.4814997141913382)),
 (421, np.float64(0.16500727800431247)),
 (422, np.float64(0.06921365347848474)),
 (423, np.float64(0.14162057587835297)),
 (424, np.float64(0.09091759878484888)),
 (425, np.float64(0.11169086950205934)),
 (426, np.float64(0.15661012853977835)),
 (427, np.float64(0.08959329736879638)),
 (428, np.float64(0.05305234639272941)),
 (429, np.float64(0.06080056831773059)),
 (430, np.float64(0.23812582155634415)),
 (431, np.float64(0.30734838752599314)),
 (432, np.float64(0.18923957654818443)),
 (433, np.float64(0.315060356913716)),
 (434, np.float64(0.05180298757836077)),
 (435, np.float64(0.0005927064043219176)),
 (436, np.float64(0.0016462710561398748)),
 (437, np.float64(0.15726584112768507)),
 (438, np.float64(0.05350316235979184)),
 (439, np.float64(0.2540232175238111)),
 (440, np.float64(0.2761516539306605)),
 (441, np.float64(0.19435989419931865)),
 (442, np.float64(0.0007902676659215948)),
 (443, np.float64(0.19352460011582018)),
 (444, np.float64(0.06309386170726096)),
 (445, np.float64(0.1428925880633071)),
 (446, np.float64(0.09052286495201839)),
 (447, np.float64(0.45559729011046723)),
 (448, np.float64(0.07368494932264065)),
 (449, np.float64(0.05879533742057396)),
 (450, np.float64(0.00019757095574697965)),
 (451, np.float64(0.003225823902473263)),
 (452, np.float64(0.0648334128041343)),
 (453, np.float64(0.0)),
 (454, np.float64(0.15428693088071546)),
 (455, np.float64(0.10680584515484931)),
 (456, np.float64(0.10865953132205151)),
 (457, np.float64(0.0979050083996542)),
 (458, np.float64(0.2139153248383186)),
 (459, np.float64(0.0007902676659215948)),
 (460, np.float64(0.06080056831773059)),
 (461, np.float64(0.220512570743754)),
 (462, np.float64(0.0757259719427527)),
 (463, np.float64(0.05688062758716908)),
 (464, np.float64(0.21502651988166893)),
 (465, np.float64(0.14947616377220896)),
 (466, np.float64(0.04138676314786143)),
 (467, np.float64(0.0)),
 (468, np.float64(0.07458911609484821)),
 (469, np.float64(0.0)),
 (470, np.float64(0.06858258221485375)),
 (471, np.float64(0.07079171727392931)),
 (472, np.float64(0.30329868907176494)),
 (473, np.float64(0.053026559754162414)),
 (474, np.float64(0.18299399818576084)),
 (475, np.float64(0.35215994553232877)),
 (476, np.float64(0.2322657332396784)),
 (477, np.float64(0.0)),
 (478, np.float64(0.20895967204602525)),
 (479, np.float64(0.10969825641826955)),
 (480, np.float64(0.5525681982992253)),
 (481, np.float64(0.07037412736032717)),
 (482, np.float64(0.27836186924305817)),
 (483, np.float64(0.0016462710561398748)),
 (484, np.float64(0.04703306105769918)),
 (485, np.float64(0.04256392221637689)),
 (486, np.float64(0.9928146517303427)),
 (487, np.float64(0.0)),
 (488, np.float64(0.000724414550325523)),
 (489, np.float64(0.001448749460475517)),
 (490, np.float64(0.05550841752392945)),
 (491, np.float64(0.17173182133544768)),
 (492, np.float64(0.0007902676659215948)),
 (493, np.float64(0.10064006238674257)),
 (494, np.float64(0.001448749460475517)),
 (495, np.float64(0.07037691607651993)),
 (496, np.float64(0.11925414615001176)),
 (497, np.float64(0.0032258239024732633)),
 (498, np.float64(0.05137978471424966)),
 (499, np.float64(0.14411001445467062)),
 (500, np.float64(0.06619854133854439)),
 (501, np.float64(0.05781041273902628)),
 (502, np.float64(0.0662641663991842)),
 (503, np.float64(0.07559686335635071)),
 (504, np.float64(0.0)),
 (505, np.float64(0.056859982377452045)),
 (506, np.float64(0.06637528186455971)),
 (507, np.float64(0.06237569711331239)),

In [267]:
# Sorting score values
similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
similarity_scores

[(841, np.float64(1.0000000000000002)),
 (615, np.float64(0.992880358436798)),
 (486, np.float64(0.9928146517303427)),
 (1103, np.float64(0.9928146517303427)),
 (1343, np.float64(0.9928146517303427)),
 (1472, np.float64(0.9928146517303427)),
 (1573, np.float64(0.9928146517303427)),
 (2458, np.float64(0.9928146517303427)),
 (2997, np.float64(0.9928146517303427)),
 (7628, np.float64(0.9736455086961724)),
 (1796, np.float64(0.9428393858444418)),
 (784, np.float64(0.9403792452530202)),
 (2416, np.float64(0.9403792452530202)),
 (206, np.float64(0.9373467960404539)),
 (4576, np.float64(0.9366725123128546)),
 (588, np.float64(0.9351298479679158)),
 (515, np.float64(0.9335544329072132)),
 (2852, np.float64(0.931411432514719)),
 (2342, np.float64(0.9312337620032821)),
 (6163, np.float64(0.9305605389269056)),
 (1930, np.float64(0.9301775677840498)),
 (1409, np.float64(0.9301118515814573)),
 (3203, np.float64(0.9301118515814573)),
 (4275, np.float64(0.9301118515814573)),
 (4314, np.float64(0.9301118515814573)),
 (5999, np.float64(0.9301118515814573)),
 (6763, np.float64(0.9300494670763534)),
 (3443, np.float64(0.9298531635277315)),
 (4498, np.float64(0.9298531635277315)),
 (719, np.float64(0.9283831695544799)),
 (7867, np.float64(0.9154888607158274)),
 (1227, np.float64(0.9099430398953716)),
 (346, np.float64(0.905340921079741)),
 (6970, np.float64(0.9041217538896997)),
 (7080, np.float64(0.8977086675661138)),
 (1184, np.float64(0.8938747747468835)),
 (182, np.float64(0.8914002498100578)),
 (271, np.float64(0.8914002498100578)),
 (3038, np.float64(0.885385396268251)),
 (1209, np.float64(0.8846498303851218)),
 (2615, np.float64(0.8846498303851218)),
 (4942, np.float64(0.878040216103861)),
 (6835, np.float64(0.8775925725564875)),
 (1931, np.float64(0.8736769487778224)),
 (9419, np.float64(0.8701134249847473)),
 (1237, np.float64(0.8697948563440301)),
 (9739, np.float64(0.8619476148555252)),
 (6392, np.float64(0.8585337170078897)),
 (3408, np.float64(0.8530454971961666)),
 (6115, np.float64(0.8526773358674895)),
 (7178, np.float64(0.8526773358674895)),
 (2981, np.float64(0.8516055020546522)),
 (2494, np.float64(0.849487861222182)),
 (6229, np.float64(0.8342215513548321)),
 (6457, np.float64(0.8276388320311701)),
 (3130, np.float64(0.8198663383302267)),
 (9740, np.float64(0.8187334960613714)),
 (3523, np.float64(0.8168354961593954)),
 (3524, np.float64(0.8168354961593954)),
 (3551, np.float64(0.8168354961593954)),
 (3976, np.float64(0.816126036760533)),
 (2633, np.float64(0.8049116159595182)),
 (2534, np.float64(0.8002177107723273)),
 (6946, np.float64(0.7967353049637315)),
 (7837, np.float64(0.7950930336632349)),
 (1678, np.float64(0.7929272358691848)),
 (2652, np.float64(0.7914870940606453)),
 (5957, np.float64(0.7836889312428572)),
 (4837, np.float64(0.7821726810455132)),
 (4120, np.float64(0.781725779482042)),
 (2712, np.float64(0.7711549665345)),
 (8200, np.float64(0.7710894598361698)),
 (2350, np.float64(0.7710237195401917)),
 (8920, np.float64(0.7710237195401917)),
 (985, np.float64(0.7641806498948377)),
 (1366, np.float64(0.7641806498948377)),
 (3565, np.float64(0.7641806498948377)),
 (919, np.float64(0.7634702256013439)),
 (4067, np.float64(0.7625144756340798)),
 (2913, np.float64(0.7579542673242684)),
 (2934, np.float64(0.7574657813322553)),
 (4701, np.float64(0.7574657813322553)),
 (6407, np.float64(0.7553592406189065)),
 (2590, np.float64(0.7509984922990427)),
 (4562, np.float64(0.7498259248304859)),
 (5788, np.float64(0.7496987545209743)),
 (4127, np.float64(0.7491809811020818)),
 (1584, np.float64(0.7415308318560996)),
 (175, np.float64(0.7390296736049681)),
 (260, np.float64(0.7387319514751336)),
 (1543, np.float64(0.7378251337712111)),
 (2952, np.float64(0.7372897828390828)),
 (510, np.float64(0.7364209444773953)),
 (2128, np.float64(0.7359700945863719)),
 (3922, np.float64(0.7357735265036015)),
 (1068, np.float64(0.7305176195159463)),
 (8850, np.float64(0.7302400718764643)),
 (10493, np.float64(0.7302400718764643)),
 (10240, np.float64(0.7157004808205633)),
 (7439, np.float64(0.7149915527826285)),
 (8480, np.float64(0.7149915527826285)),
 (10224, np.float64(0.7149915527826285)),
 (1752, np.float64(0.7149258039908016)),
 (6290, np.float64(0.7149258039908016)),
 (8534, np.float64(0.7149258039908016)),
 (8655, np.float64(0.7149258039908016)),
 (3341, np.float64(0.7121884947050304)),
 (1828, np.float64(0.7049288020303859)),
 (7125, np.float64(0.704581744697372)),
 (6285, np.float64(0.7039976742088974)),
 (7386, np.float64(0.7039976742088974)),
 (734, np.float64(0.7018659618985505)),
 (10042, np.float64(0.7016287357443118)),
 (4605, np.float64(0.7000487178753383)),
 (1577, np.float64(0.6993414917419727)),
 (2585, np.float64(0.6988782656468246)),
 (683, np.float64(0.6985150274274388)),
 (3664, np.float64(0.698156217886779)),
 (6048, np.float64(0.6974088852996781)),
 (5121, np.float64(0.6965917317149403)),
 (6182, np.float64(0.6963951099586568)),
 (4659, np.float64(0.6957191429574616)),
 (6196, np.float64(0.6919558517577828)),
 (3759, np.float64(0.691509816290194)),
 (3271, np.float64(0.6892211158740182)),
 (2933, np.float64(0.6876015597601577)),
 (3927, np.float64(0.6876015597601577)),
 (3984, np.float64(0.6876015597601577)),
 (1289, np.float64(0.6871085953243521)),
 (1428, np.float64(0.6871085953243521)),
 (3930, np.float64(0.6861811544846255)),
 (1706, np.float64(0.6839748408509165)),
 (3529, np.float64(0.6795300283730529)),
 (4012, np.float64(0.6760119359765215)),
 (1417, np.float64(0.6725866868387237)),
 (582, np.float64(0.6720926231755561)),
 (2936, np.float64(0.6718201098971284)),
 (1448, np.float64(0.6714933681426749)),
 (5054, np.float64(0.6714933681426749)),
 (6926, np.float64(0.6709935353215987)),
 (7026, np.float64(0.6709935353215987)),
 (6121, np.float64(0.6707826850001815)),
 (3505, np.float64(0.6689345453375601)),
 (178, np.float64(0.6677489870886906)),
 (2647, np.float64(0.6676470016539552)),
 (6, np.float64(0.6675139007799272)),
 (1842, np.float64(0.6671210946367488)),
 (10901, np.float64(0.6670390205818595)),
 (2259, np.float64(0.6669732645277747)),
 (9811, np.float64(0.666644873376726)),
 (112, np.float64(0.6636572571078009)),
 (9673, np.float64(0.6631114173106549)),
 (538, np.float64(0.6622076612161923)),
 (946, np.float64(0.6614811600327035)),
 (1131, np.float64(0.6614811600327035)),
 (3024, np.float64(0.6609589029526224)),
 (146, np.float64(0.6608530913586563)),
 (10768, np.float64(0.6605923219043296)),
 (145, np.float64(0.6604699616451298)),
 (202, np.float64(0.6604699616451298)),
 (5429, np.float64(0.6602862368953156)),
 (1974, np.float64(0.6600138633794436)),
 (2046, np.float64(0.6600138633794436)),
 (2108, np.float64(0.6600138633794436)),
 (10458, np.float64(0.6600138633794436)),
 (821, np.float64(0.6598358678555494)),
 (5459, np.float64(0.6566386292449429)),
 (3556, np.float64(0.6529673778470678)),
 (1498, np.float64(0.6518922531228306)),
 (2867, np.float64(0.6518646820679107)),
 (2119, np.float64(0.6512721862519923)),
 (352, np.float64(0.6512064278100709)),
 (753, np.float64(0.6512064278100709)),
 (941, np.float64(0.6512064278100709)),
 (1171, np.float64(0.6512064278100709)),
 (1576, np.float64(0.6512064278100709)),
 (1793, np.float64(0.6512064278100709)),
 (1795, np.float64(0.6512064278100709)),
 (1829, np.float64(0.6512064278100709)),
 (2161, np.float64(0.6512064278100709)),
 (2202, np.float64(0.6512064278100709)),
 (2492, np.float64(0.6512064278100709)),
 (2723, np.float64(0.6512064278100709)),
 (3202, np.float64(0.6512064278100709)),
 (3264, np.float64(0.6512064278100709)),
 (3839, np.float64(0.6512064278100709)),
 (4316, np.float64(0.6510586714449889)),
 (4759, np.float64(0.6510586714449889)),
 (3296, np.float64(0.6506977963046913)),
 (3439, np.float64(0.6506977963046913)),
 (6010, np.float64(0.6506781806654354)),
 (11930, np.float64(0.6502696547003509)),
 (6143, np.float64(0.6444198760071239)),
 (3520, np.float64(0.6436720757757243)),
 (8923, np.float64(0.6428463976417743)),
 (3115, np.float64(0.6422081227747559)),
 (11089, np.float64(0.6421358918281861)),
 (1127, np.float64(0.6380372578317369)),
 (2351, np.float64(0.6380372578317369)),
 (1150, np.float64(0.6379718839394093)),
 (3778, np.float64(0.6375806531635201)),
 (6091, np.float64(0.6354759278381538)),
 (7536, np.float64(0.6349829538482641)),
 (10048, np.float64(0.6327991285799572)),
 (10652, np.float64(0.6319025294115558)),
 (579, np.float64(0.6316700649153466)),
 (2709, np.float64(0.6312072515979376)),
 (120, np.float64(0.6308725193752669)),
 (4199, np.float64(0.6293217555465246)),
 (7559, np.float64(0.6286388688310747)),
 (7615, np.float64(0.6281738434849595)),
 (7864, np.float64(0.6280579876310789)),
 (7436, np.float64(0.6279927964653432)),
 (10121, np.float64(0.6261116027030266)),
 (7147, np.float64(0.6260475480186627)),
 (4608, np.float64(0.6235631430565662)),
 (1203, np.float64(0.6225453059501348)),
 (10423, np.float64(0.6219757362963212)),
 (876, np.float64(0.620977333872144)),
 (86, np.float64(0.6205350738429164)),
 (717, np.float64(0.6191399721283338)),
 (10899, np.float64(0.6190743963634792)),
 (961, np.float64(0.6190086330453053)),
 (1069, np.float64(0.6190086330453053)),
 (3533, np.float64(0.6190086330453053)),
 (74, np.float64(0.6171115018525477)),
 (231, np.float64(0.6170457382370999)),
 (241, np.float64(0.6170457382370999)),
 (896, np.float64(0.6170457382370999)),
 (7122, np.float64(0.6169912449173001)),
 (1105, np.float64(0.614909199741179)),
 (3288, np.float64(0.6141171056526534)),
 (2019, np.float64(0.6084456174625005)),
 (10052, np.float64(0.6069336039799547)),
 (1600, np.float64(0.6067550858189507)),
 (2531, np.float64(0.6057749207493809)),
 (4241, np.float64(0.605546830988987)),
 (3597, np.float64(0.6052671523216729)),
 (281, np.float64(0.6048994698430619)),
 (10051, np.float64(0.6048132112914764)),
 (10049, np.float64(0.6047476290173981)),
 (10046, np.float64(0.6046818635294811)),
 (10047, np.float64(0.6046818635294811)),
 (10050, np.float64(0.6046818635294811)),
 (3781, np.float64(0.6036058111132858)),
 (815, np.float64(0.6034332169191405)),
 (12020, np.float64(0.602945190264667)),
 (1271, np.float64(0.6020104854689711)),
 (3543, np.float64(0.6019467264894066)),
 (1244, np.float64(0.6013646791270575)),
 (1694, np.float64(0.6013646791270575)),
 (2503, np.float64(0.6001580060193284)),
 (4548, np.float64(0.6000963373250546)),
 (6250, np.float64(0.599285459809736)),
 (7520, np.float64(0.5986341503817663)),
 (2681, np.float64(0.5972028696069511)),
 (4785, np.float64(0.5970501192913826)),
 (10629, np.float64(0.5967487276722508)),
 (3307, np.float64(0.5959803146861837)),
 (10398, np.float64(0.5957773455791117)),
 (8748, np.float64(0.5957233868802553)),
 (8749, np.float64(0.5953981616043926)),
 (1333, np.float64(0.5947209553178021)),
 (5785, np.float64(0.5947209553178021)),
 (333, np.float64(0.5941873088992133)),
 (607, np.float64(0.5941873088992133)),
 (2515, np.float64(0.5941873088992133)),
 (7081, np.float64(0.5936733429766001)),
 (11031, np.float64(0.5929545681401914)),
 (1108, np.float64(0.5924167827504168)),
 (10826, np.float64(0.5906368916258092)),
 (5264, np.float64(0.5905090908802896)),
 (4417, np.float64(0.590456452442597)),
 (7353, np.float64(0.5898612518157863)),
 (6594, np.float64(0.5897954840733752)),
 (11528, np.float64(0.589482025293847)),
 (3661, np.float64(0.5890914457438872)),
 (2184, np.float64(0.5887755729728437)),
 (3052, np.float64(0.5887755729728437)),
 (3289, np.float64(0.5887755729728437)),
 (513, np.float64(0.5880449721508506)),
 (7390, np.float64(0.588005492700764)),
 (3757, np.float64(0.5873945902196951)),
 (4521, np.float64(0.5873945902196951)),
 (2965, np.float64(0.5866809263398771)),
 (3184, np.float64(0.5866809263398771)),
 (8659, np.float64(0.5855156914755149)),
 (6293, np.float64(0.5853217096063407)),
 (2015, np.float64(0.58484423109503)),
 (2588, np.float64(0.58484423109503)),
 (2925, np.float64(0.58484423109503)),
 (3992, np.float64(0.58484423109503)),
 (9742, np.float64(0.58484423109503)),
 (9575, np.float64(0.5841451738524048)),
 (3476, np.float64(0.5824845688319374)),
 (9390, np.float64(0.5822504266927807)),
 (2882, np.float64(0.5807905077204522)),
 (3804, np.float64(0.5784293612667761)),
 (3802, np.float64(0.5781100146478563)),
 (4988, np.float64(0.5781100146478563)),
 (4200, np.float64(0.5779818041338961)),
 (8919, np.float64(0.5772586116221584)),
 (3316, np.float64(0.5742395624205471)),
 (3436, np.float64(0.5737236823573435)),
 (9134, np.float64(0.5733809292982726)),
 (6588, np.float64(0.5733151590599692)),
 (400, np.float64(0.5722406018207762)),
 (1488, np.float64(0.5716423637899242)),
 (3116, np.float64(0.5711199943231917)),
 (5850, np.float64(0.5707757189503769)),
 (521, np.float64(0.5707099483175226)),
 (1459, np.float64(0.5707099483175226)),
 (10551, np.float64(0.5707099483175226)),
 (1013, np.float64(0.5704285779263201)),
 (859, np.float64(0.5697725712878992)),
 (106, np.float64(0.5692187579540008)),
 (814, np.float64(0.5676098984087204)),
 (996, np.float64(0.5676098984087204)),
 (4644, np.float64(0.5675460196069898)),
 (2733, np.float64(0.567399116039314)),
 (2823, np.float64(0.567333344895084)),
 (611, np.float64(0.5668319920041609)),
 (881, np.float64(0.5668319920041609)),
 (944, np.float64(0.5668319920041609)),
 (1023, np.float64(0.5668319920041609)),
 (1196, np.float64(0.5668319920041609)),
 (1478, np.float64(0.5668319920041609)),
 (1753, np.float64(0.5665788407140885)),
 (9844, np.float64(0.5664574593705972)),
 (733, np.float64(0.5663683140933404)),
 (2232, np.float64(0.5663484244503523)),
 (2946, np.float64(0.5661152411972837)),
 (5503, np.float64(0.5660911729564772)),
 (3318, np.float64(0.5658331483082998)),
 (995, np.float64(0.5657586725222797)),
 (526, np.float64(0.5657514343868199)),
 (5571, np.float64(0.5653593764534707)),
 (8191, np.float64(0.5649551335553072)),
 (10432, np.float64(0.5644983264868336)),
 (10657, np.float64(0.563793743282519)),
 (1589, np.float64(0.5635004627738411)),
 (3494, np.float64(0.5635004627738411)),
 (3977, np.float64(0.5635004627738411)),
 (10752, np.float64(0.5606919996540104)),
 (4045, np.float64(0.5606508336345373)),
 (6440, np.float64(0.5600404162343019)),
 (3680, np.float64(0.5598754514867637)),
 (866, np.float64(0.5586513684290076)),
 (6015, np.float64(0.5576632493383906)),
 (4963, np.float64(0.5568570603245003)),
 (10970, np.float64(0.5564283531941274)),
 (4093, np.float64(0.5554601829116689)),
 (12221, np.float64(0.5551646728171414)),
 (845, np.float64(0.5548405660102339)),
 (980, np.float64(0.5541621738460253)),
 (416, np.float64(0.5533464157632954)),
 (1499, np.float64(0.5533464157632954)),
 (4413, np.float64(0.5530441098786104)),
 (4382, np.float64(0.5528426800954199)),
 (194, np.float64(0.5525681982992253)),
 (480, np.float64(0.5525681982992253)),
 (11034, np.float64(0.5525681982992253)),
 (4293, np.float64(0.5514974352851376)),
 (355, np.float64(0.5513737485063366)),
 (740, np.float64(0.5513737485063366)),
 (1956, np.float64(0.5513737485063366)),
 (2020, np.float64(0.5513737485063366)),
 (9741, np.float64(0.5509463582647417)),
 (7419, np.float64(0.5505971642742578)),
 (6381, np.float64(0.5502429638192416)),
 (5714, np.float64(0.5500345884675932)),
 (6350, np.float64(0.5499689813053841)),
 (10942, np.float64(0.5499689813053841)),
 (1397, np.float64(0.5499032075214159)),
 (2478, np.float64(0.5499032075214159)),
 (3735, np.float64(0.5499032075214159)),
 (4713, np.float64(0.5499032075214159)),
 (6929, np.float64(0.5499032075214159)),
 (7008, np.float64(0.5499032075214159)),
 (7310, np.float64(0.5499032075214159)),
 (9009, np.float64(0.5499032075214159)),
 (8526, np.float64(0.548921647197953)),
 (4444, np.float64(0.5489036006252898)),
 (1732, np.float64(0.5484310069264204)),
 (4155, np.float64(0.5478565154353315)),
 (5218, np.float64(0.5476193179329574)),
 (5865, np.float64(0.5474177681473378)),
 (4041, np.float64(0.5464597337129043)),
 (5167, np.float64(0.5464597337129043)),
 (8016, np.float64(0.5450362338879512)),
 (1762, np.float64(0.5447981442898909)),
 (5189, np.float64(0.5441197116556892)),
 (8060, np.float64(0.5437757770062935)),
 (11012, np.float64(0.5433280330997341)),
 (6716, np.float64(0.5418690016666318)),
 (8345, np.float64(0.5418093849019009)),
 (10661, np.float64(0.5410905339019234)),
 (1729, np.float64(0.540984105488536)),
 (4171, np.float64(0.5402912343397234)),
 (3035, np.float64(0.5373485745341691)),
 (8985, np.float64(0.5368797954746927)),
 (6198, np.float64(0.5356569498559043)),
 (2167, np.float64(0.5349084429730918)),
 (9891, np.float64(0.5332266354060605)),
 (6331, np.float64(0.5318796271052062)),
 (4986, np.float64(0.5318404490184429)),
 (8312, np.float64(0.5313846912619679)),
 (10659, np.float64(0.5313846912619679)),
 (1219, np.float64(0.5310919025582879)),
 (2251, np.float64(0.5302796695461154)),
 (5332, np.float64(0.5302796695461154)),
 (10907, np.float64(0.5299596290479233)),
 (4414, np.float64(0.5292342459774825)),
 (4741, np.float64(0.5292342459774825)),
 (4780, np.float64(0.5292342459774825)),
 (4424, np.float64(0.5283446091129209)),
 (4558, np.float64(0.5282300630260602)),
 (9913, np.float64(0.5282092849391643)),
 (9962, np.float64(0.5282092849391643)),
 (10350, np.float64(0.5282092849391643)),
 (9601, np.float64(0.5278119186466697)),
 (10339, np.float64(0.5277940162797716)),
 (10370, np.float64(0.5277940162797716)),
 (4717, np.float64(0.5273740526768017)),
 (7363, np.float64(0.5266256321817678)),
 (9148, np.float64(0.5249398388220075)),
 (2617, np.float64(0.5243362014289213)),
 (3007, np.float64(0.5242893592719561)),
 (11236, np.float64(0.5242156350867756)),
 (5441, np.float64(0.5242069498826039)),
 (5839, np.float64(0.5240434161189876)),
 (11565, np.float64(0.5240187783783521)),
 (7451, np.float64(0.5239243242428161)),
 (1192, np.float64(0.5231408651174652)),
 (4198, np.float64(0.5226444591801936)),
 (4422, np.float64(0.5223339701816406)),
 (4263, np.float64(0.5222689835126463)),
 (1636, np.float64(0.5221649305543685)),
 (1895, np.float64(0.5221649305543685)),
 (2311, np.float64(0.5221649305543685)),
 (3273, np.float64(0.5221649305543685)),
 (5404, np.float64(0.5221649305543685)),
 (6911, np.float64(0.5221649305543685)),
 (4144, np.float64(0.522094803682533)),
 (4965, np.float64(0.5215158494408637)),
 (1374, np.float64(0.5214736129354859)),
 (2644, np.float64(0.5214500713477596)),
 (3228, np.float64(0.5214500713477596)),
 (3904, np.float64(0.5214500713477596)),
 (10486, np.float64(0.5214500713477596)),
 (11087, np.float64(0.5214500713477596)),
 (1792, np.float64(0.5205315707962468)),
 (2479, np.float64(0.5188360800255117)),
 (8882, np.float64(0.5187609634110427)),
 (3317, np.float64(0.5181286839845307)),
 (830, np.float64(0.517334247898898)),
 (8872, np.float64(0.5164852094148753)),
 (8875, np.float64(0.5164852094148753)),
 (8876, np.float64(0.5164852094148753)),
 (3022, np.float64(0.515985799913543)),
 (8505, np.float64(0.5153872858453197)),
 (5308, np.float64(0.5152892578344803)),
 (2093, np.float64(0.5149868754343198)),
 (5517, np.float64(0.5148705626520406)),
 (8870, np.float64(0.5148705626520406)),
 (8871, np.float64(0.5142213489747245)),
 (8874, np.float64(0.5142213489747245)),
 (8877, np.float64(0.5141555697768916)),
 (8878, np.float64(0.5141555697768916)),
 (8879, np.float64(0.5141555697768916)),
 (10465, np.float64(0.5141555697768916)),
 (10466, np.float64(0.5141555697768916)),
 (6087, np.float64(0.5135726415749777)),
 (3387, np.float64(0.5134091792846406)),
 (10783, np.float64(0.5133922669420117)),
 (5048, np.float64(0.5123937268010287)),
 (9747, np.float64(0.5118113464758198)),
 (543, np.float64(0.50924908359743)),
 (793, np.float64(0.50924908359743)),
 (6199, np.float64(0.5090454370310669)),
 (1922, np.float64(0.5087972634397256)),
 (7995, np.float64(0.5085951270722315)),
 (6992, np.float64(0.506976933782527)),
 (3344, np.float64(0.5058872064293846)),
 (644, np.float64(0.5057796877671431)),
 (4375, np.float64(0.5050905030603481)),
 (3920, np.float64(0.504375330966615)),
 (4057, np.float64(0.5011095110344398)),
 (8918, np.float64(0.501059262064796)),

In [268]:
# Removing same Anime cause we dont want to recommend Naruto to someone searching Naruto.
top_n = 10
similarity_scores = similarity_scores[1:top_n+1]
similarity_scores

[(615, np.float64(0.992880358436798)),
 (486, np.float64(0.9928146517303427)),
 (1103, np.float64(0.9928146517303427)),
 (1343, np.float64(0.9928146517303427)),
 (1472, np.float64(0.9928146517303427)),
 (1573, np.float64(0.9928146517303427)),
 (2458, np.float64(0.9928146517303427)),
 (2997, np.float64(0.9928146517303427)),
 (7628, np.float64(0.9736455086961724)),
 (1796, np.float64(0.9428393858444418))]

In [269]:
# Extracting anime indices
anime_indices = [i[0] for i in similarity_scores]

In [270]:
# Displaying recommended
df[['name', 'genre', 'rating']].iloc[anime_indices]

,name,genre,rating
615,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",0.752701
486,Boruto: Naruto the Movie,"Action, Comedy, Martial Arts, Shounen, Super P...",0.763505
1103,Boruto: Naruto the Movie - Naruto ga Hokage ni...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.721489
1343,Naruto x UT,"Action, Comedy, Martial Arts, Shounen, Super P...",0.709484
1472,Naruto: Shippuuden Movie 4 - The Lost Tower,"Action, Comedy, Martial Arts, Shounen, Super P...",0.703481
1573,Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.699880
2458,Naruto Shippuuden: Sunny Side Battle,"Action, Comedy, Martial Arts, Shounen, Super P...",0.671068
2997,Naruto Soyokazeden Movie: Naruto to Mashin to ...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.653061
7628,Kyutai Panic Adventure!,"Action, Martial Arts, Shounen, Super Power",0.424970
1796,Rekka no Honoo,"Action, Adventure, Martial Arts, Shounen, Supe...",0.692677

In [271]:
# Testing recommendation system
recommend_anime("Naruto")

,name,genre,rating
615,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",0.752701
486,Boruto: Naruto the Movie,"Action, Comedy, Martial Arts, Shounen, Super P...",0.763505
1103,Boruto: Naruto the Movie - Naruto ga Hokage ni...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.721489
1343,Naruto x UT,"Action, Comedy, Martial Arts, Shounen, Super P...",0.709484
1472,Naruto: Shippuuden Movie 4 - The Lost Tower,"Action, Comedy, Martial Arts, Shounen, Super P...",0.703481
1573,Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsu...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.699880
2458,Naruto Shippuuden: Sunny Side Battle,"Action, Comedy, Martial Arts, Shounen, Super P...",0.671068
2997,Naruto Soyokazeden Movie: Naruto to Mashin to ...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.653061
7628,Kyutai Panic Adventure!,"Action, Martial Arts, Shounen, Super Power",0.424970
1796,Rekka no Honoo,"Action, Adventure, Martial Arts, Shounen, Supe...",0.692677

In [272]:
# Adding threshold
def recommend_with_threshold(
        title,
        threshold=0.5):

    idx = indices[title]

    similarity_scores = list(enumerate(cosine_sim[idx]))

    filtered_scores = []

    for anime_idx, score in similarity_scores:

        if score > threshold:
            filtered_scores.append((anime_idx, score))

    filtered_scores = sorted(filtered_scores, key=lambda x: x[1], reverse=True)

    filtered_scores = filtered_scores[1:]

    anime_indices = [i[0] for i in filtered_scores]

    return df[['name', 'genre','rating']].iloc[anime_indices]

In [273]:
# Experimenting with threshold with 0.3
recommend_with_threshold("Naruto", threshold=0.3)

,name,genre,rating
615,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",0.752701
486,Boruto: Naruto the Movie,"Action, Comedy, Martial Arts, Shounen, Super P...",0.763505
1103,Boruto: Naruto the Movie - Naruto ga Hokage ni...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.721489
1343,Naruto x UT,"Action, Comedy, Martial Arts, Shounen, Super P...",0.709484
1472,Naruto: Shippuuden Movie 4 - The Lost Tower,"Action, Comedy, Martial Arts, Shounen, Super P...",0.703481
...,...,...,...
1307,City Hunter: Ai to Shukumei no Magnum,"Action, Comedy, Mystery, Shounen",0.710684
1375,City Hunter: The Secret Service,"Action, Comedy, Mystery, Shounen",0.707083
1405,City Hunter: Hyakuman Dollar no Inbou,"Action, Comedy, Mystery, Shounen",0.705882
1523,City Hunter: Bay City Wars,"Action, Comedy, Mystery, Shounen",0.701080
4249,Lupin III: Green vs. Red,"Action, Comedy, Mystery, Shounen",0.612245

In [274]:
# Experiment with treshold 0.5
recommend_with_threshold("Naruto", threshold=0.5)

,name,genre,rating
615,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",0.752701
486,Boruto: Naruto the Movie,"Action, Comedy, Martial Arts, Shounen, Super P...",0.763505
1103,Boruto: Naruto the Movie - Naruto ga Hokage ni...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.721489
1343,Naruto x UT,"Action, Comedy, Martial Arts, Shounen, Super P...",0.709484
1472,Naruto: Shippuuden Movie 4 - The Lost Tower,"Action, Comedy, Martial Arts, Shounen, Super P...",0.703481
...,...,...,...
5748,Highschool Aurabuster: Hikari no Mezame,"Drama, Fantasy, Super Power",0.563025
5307,11eyes,"Action, Ecchi, Super Power, Supernatural",0.578631
1263,Sekirei: Pure Engagement,"Action, Comedy, Ecchi, Harem, Super Power",0.713085
1949,Sekirei,"Action, Comedy, Ecchi, Harem, Super Power",0.687875
6130,Yumeria,"Action, Comedy, Ecchi, Harem, Super Power",0.549820

In [275]:
# Experiment with threshold 0.7
recommend_with_threshold("Naruto", threshold=0.7)

,name,genre,rating
615,Naruto: Shippuuden,"Action, Comedy, Martial Arts, Shounen, Super P...",0.752701
486,Boruto: Naruto the Movie,"Action, Comedy, Martial Arts, Shounen, Super P...",0.763505
1103,Boruto: Naruto the Movie - Naruto ga Hokage ni...,"Action, Comedy, Martial Arts, Shounen, Super P...",0.721489
1343,Naruto x UT,"Action, Comedy, Martial Arts, Shounen, Super P...",0.709484
1472,Naruto: Shippuuden Movie 4 - The Lost Tower,"Action, Comedy, Martial Arts, Shounen, Super P...",0.703481
...,...,...,...
6285,Big Order,"Action, Shounen, Super Power",0.541417
7386,Kyutai Panic Adventure Returns!,"Action, Shounen, Super Power",0.454982
734,Ranma ½ OVA,"Comedy, Martial Arts, Romance, Shounen",0.744298
10042,Pyun Pyun Maru,"Comedy, Martial Arts",0.655462
4605,Kizuna Ichigeki,"Comedy, Martial Arts",0.601441

In [276]:
# Comparing thresholds
for t in [0.3, 0.5, 0.7]:

    result = recommend_with_threshold("Naruto", threshold=t)

    print("Threshold =", t)
    print("Number of Recommendations =", len(result))
    print("-"*50)

Threshold = 0.3
Number of Recommendations = 823
--------------------------------------------------
Threshold = 0.5
Number of Recommendations = 494
--------------------------------------------------
Threshold = 0.7
Number of Recommendations = 113
--------------------------------------------------

#### Performance Analysis
1. At threshold 0.3, the system generated a large number of recommendations. Some recommendations were less relevant because the similarity requirement was low.
2. At threshold 0.5, the recommendations were more balanced and relevant.
3. At threshold 0.7, only highly similar anime were recommended, resulting in fewer but more accurate suggestions.

#### Areas of improovemnt
1. Current system uses anime features only. Using user-watch history would improve personalization.
2. Current approach is content-based. Collaborative filtering can capture user preferences better.

#### Interview Questions

1. Difference between User-Based and Item-Based Collaborative Filtering

User-Based Collaborative Filtering
"Users similar to me liked these items."

Example:
           
            Rasika likes:
            
            Naruto
            
            One Piece

User B likes:

            Naruto
          
            One Piece
          
            Bleach

Recommend:
           
            Bleach

Because both users have similar preferences.

Item-Based Collaborative Filtering
"Items similar to the item you liked."

Example:

            Naruto is similar to:

            Bleach
            
            One Piece

Recommend:
            
            Bleach
            
            One Piece

2. What is Collaborative Filtering?

Collaborative filtering recommends items based on user behavior.

It assumes, Users with similar interests will like similar items.