In [1]:
# importing libraries
import pandas as pd # for reading csv files and dataset handling
import numpy as np # for performing mathematical operations
import matplotlib.pyplot as plt # for graphical visualization 
import seaborn as sns # for statistical graph visualization
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder # for feature scaling and encoding

In [2]:
# loding dataset
df = pd.read_csv(r"C:\Users\rasika\Downloads\Data Trasformation (1)\adult_with_headers (1).csv")
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
# Summary of dataset
df.info() # number of entries (rows), number of columns, columns(features) and there datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [4]:
# Summary Statistics 
df.describe() # count of data entries in each features within dataset, mean, standard deviation interquartile range, min, max of each features

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [5]:
# cheking missing values, missing values are often stored as the string like ' ?' in here.
(df[['age',	'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain',	'capital_loss',	'hours_per_week', 'native_country']] == ' ?').sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
dtype: int64

In [6]:
df.replace(' ?', np.nan, inplace = True) 
# replacing ' ?' with null because Machine learning algorithms don't recognize this as missing data. 
# Replacing it with np.nan allows to detect missing values using isnull()

In [7]:
df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [8]:
# As missing values are present only in categorical type of features replacing them with mode.
for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0])

In [26]:
df.isnull().sum()

age                 0
workclass           0
fnlwgt              0
education           0
education_num       0
marital_status      0
occupation          0
relationship        0
race                0
sex                 0
capital_gain        0
capital_loss        0
hours_per_week      0
native_country      0
income              0
net_capital         0
age_group           0
capital_gain_log    0
dtype: int64

In [10]:
# Separating numerical and categorical columns to easily perform scaling and encoding

num_cols = df.select_dtypes(include = 'int').columns
cat_cols = df.select_dtypes(include = 'object').columns

print(num_cols)
print(cat_cols)

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')
Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [11]:
# creating the numeric DataFrame
df_num = df[num_cols]

In [12]:
print(df_num.head())

   age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40

In [13]:
df_num.dtypes

age               int64
fnlwgt            int64
education_num     int64
capital_gain      int64
capital_loss      int64
hours_per_week    int64
dtype: object

##### The numerical columns in the Adult dataset (such as age, fnlwgt, capital_gain, capital_loss, and hours_per_week) have very different ranges. For example, fnlwgt contains values in hundreds of thousands, while hours_per_week typically ranges from 1 to 99. Standard Scaling standardizes these features so that they have a similar scale with mean 0 and standard deviation 1.

In [14]:
# StandardScaling
sc = StandardScaler()
x_sc = sc.fit_transform(df_num)
x_sc

array([[ 0.03067056, -1.06361075,  1.13473876,  0.1484529 , -0.21665953,
        -0.03542945],
       [ 0.83710898, -1.008707  ,  1.13473876, -0.14592048, -0.21665953,
        -2.22215312],
       [-0.04264203,  0.2450785 , -0.42005962, -0.14592048, -0.21665953,
        -0.03542945],
       ...,
       [ 1.42360965, -0.35877741, -0.42005962, -0.14592048, -0.21665953,
        -0.03542945],
       [-1.21564337,  0.11095988, -0.42005962, -0.14592048, -0.21665953,
        -1.65522476],
       [ 0.98373415,  0.92989258, -0.42005962,  1.88842434, -0.21665953,
        -0.03542945]], shape=(32561, 6))

##### Min-Max Scaling transforms all numerical features to a fixed range between 0 and 1. This makes the values easier to interpret and ensures that no feature has a larger numerical range than another.

In [15]:
# minmax Scaling
mm = MinMaxScaler()
x_mm = mm.fit_transform(df_num)
x_mm

array([[0.30136986, 0.0443019 , 0.8       , 0.02174022, 0.        ,
        0.39795918],
       [0.45205479, 0.0482376 , 0.8       , 0.        , 0.        ,
        0.12244898],
       [0.28767123, 0.13811345, 0.53333333, 0.        , 0.        ,
        0.39795918],
       ...,
       [0.56164384, 0.09482688, 0.53333333, 0.        , 0.        ,
        0.39795918],
       [0.06849315, 0.12849934, 0.53333333, 0.        , 0.        ,
        0.19387755],
       [0.47945205, 0.18720338, 0.53333333, 0.1502415 , 0.        ,
        0.39795918]], shape=(32561, 6))

### Encoding Techniques

In [16]:
# to check for categories of  each features 
for col in cat_cols:
    print(col, df[col].nunique())

workclass 8
education 16
marital_status 7
occupation 14
relationship 6
race 5
sex 2
native_country 41
income 2

### Applying LabelEncoding to:
1. workclass
2. education
3. marital_status
4. occupation
5. relationship
6. race
7. native_country
8. income even if it have 2 categories it is target column so it will handle with label encoding

### Appling OneHotEncoding to 
1. sex

In [17]:
le = LabelEncoder() # assign values to categories
label_cols = ['workclass', 
              'education', 
              'marital_status', 
              'occupation', 
              'relationship', 
              'race', 
              'native_country', 
              'income']
for cols in label_cols:
    df[cols] = le.fit_transform(df[cols])
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,6,77516,9,13,4,0,1,4,Male,2174,0,40,38,0
1,50,5,83311,9,13,2,3,0,4,Male,0,0,13,38,0
2,38,3,215646,11,9,0,5,1,4,Male,0,0,40,38,0
3,53,3,234721,1,7,2,5,0,2,Male,0,0,40,38,0
4,28,3,338409,9,13,2,9,5,2,Female,0,0,40,4,0

In [27]:
oe = OneHotEncoder() # converts categorical value into binary vectors 0 and 1
sex = oe.fit_transform(df[['sex']]).toarray().astype('int')
encoded = pd.DataFrame(sex, columns=oe.get_feature_names_out(['sex']))
encoded

       sex_ Female  sex_ Male
0                0          1
1                0          1
2                0          1
3                0          1
4                1          0
...            ...        ...
32556            1          0
32557            0          1
32558            1          0
32559            0          1
32560            1          0

[32561 rows x 2 columns]

### One-Hot Encoding
Pros
Does not create any order or ranking among categories.
1. Suitable for nominal categorical data such as gender in this dataset.
2. Prevents the model from assuming one category is greater than another.

Cons
1. Increases the number of columns in the dataset.
2. Can lead to high dimensionality when a feature has many unique categories.
3. Requires more memory and computational resources.
Example:
Sex - 
Male,
Female

### Label Encoding
Pros
1. Simple and easy to implement.
2. Does not increase the number of columns.

Cons
1. Introduces numerical labels that may imply an order where none exists.
2. Different labels may be interpreted as having greater or lesser importance.

### Feature Engineering

In [20]:
# Net Capital - 
# The dataset contains two financial columns:  capital_gain, capital_loss
# Instead of treating them separately, we can create a new feature representing the overall capital position of an individual.
# Combines gains and losses into a single meaningful feature.
# Represents the individual's net financial benefit.
# May have a stronger relationship with income than the original features separately.

df['net_capital'] = df['capital_gain'] - df['capital_loss']
df[['capital_gain', 'capital_loss', 'net_capital']].head()

   capital_gain  capital_loss  net_capital
0          2174             0         2174
1             0             0            0
2             0             0            0
3             0             0            0
4             0             0            0

In [21]:
# Working Age Group
# People in different age groups often have different earning capacities and work experience levels.
# Groups similar ages together.
# Income often varies across age groups due to experience and seniority.

df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 25, 45, 65, 100],
    labels=['Young', 'Adult', 'Middle_Aged', 'Senior']
)
df[['age', 'age_group']].head()

   age    age_group
0   39        Adult
1   50  Middle_Aged
2   38        Adult
3   53  Middle_Aged
4   28        Adult

In [22]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,net_capital,age_group
0,39,6,77516,9,13,4,0,1,4,Male,2174,0,40,38,0,2174,Adult
1,50,5,83311,9,13,2,3,0,4,Male,0,0,13,38,0,0,Middle_Aged
2,38,3,215646,11,9,0,5,1,4,Male,0,0,40,38,0,0,Adult
3,53,3,234721,1,7,2,5,0,2,Male,0,0,40,38,0,0,Middle_Aged
4,28,3,338409,9,13,2,9,5,2,Female,0,0,40,4,0,0,Adult

### Transformation of Skewed Feature

In [28]:
# Checking Skewness
num_cols.skew()

age                  0.558743
workclass            1.167150
fnlwgt               1.446980
education           -0.934042
education_num       -0.311676
marital_status      -0.013508
occupation           0.126728
relationship         0.786818
race                -2.435386
capital_gain        11.953848
capital_loss         4.594629
hours_per_week       0.227643
native_country      -4.205965
income               1.212430
net_capital         11.871934
capital_gain_log     3.096144
dtype: float64

In [24]:
# capital_gain is usually highly positively skewed because many values are 0 while a few values are extremely large.
# Applying Log Transformation to reduce the impact of extremely large values, Reduces skewness

df['capital_gain_log'] = np.log1p(df['capital_gain'])
df[['capital_gain', 'capital_gain_log']].head()

   capital_gain  capital_gain_log
0          2174          7.684784
1             0          0.000000
2             0          0.000000
3             0          0.000000
4             0          0.000000

In [30]:
# Checking Skewness
num_cols.skew()

age                  0.558743
workclass            1.167150
fnlwgt               1.446980
education           -0.934042
education_num       -0.311676
marital_status      -0.013508
occupation           0.126728
relationship         0.786818
race                -2.435386
capital_gain        11.953848
capital_loss         4.594629
hours_per_week       0.227643
native_country      -4.205965
income               1.212430
net_capital         11.871934
capital_gain_log     3.096144
dtype: float64